backend:
  name: git-gateway
  branch: main

media_folder: "images/assets"
public_folder: "/images/assets"

collections:
  - name: "seiten"
    label: "Seiteninhalte"
    files:
      - label: "Hauptinhalte"
        name: "startseite"
        file: "inhalt.json"
        fields:
          # Hero Bereich
          - label: "Hero Bereich"
            name: "hero"
            widget: "object"
            fields:
              - {label: "Hintergrundbild", name: "image", widget: "image"}
              - {label: "Titel", name: "title", widget: "string"}
              - {label: "Kicker (DE)", name: "kicker_de", widget: "string"}
              - {label: "Kicker (EN)", name: "kicker_en", widget: "string"}
              - {label: "Untertitel (DE)", name: "sub_de", widget: "text"}
              - {label: "Untertitel (EN)", name: "sub_en", widget: "text"}

          # Über mich Bereich
          - label: "Über mich Bereich"
            name: "about"
            widget: "object"
            fields:
              - {label: "Bild", name: "image", widget: "image"}
              - {label: "Titel (DE)", name: "title_de", widget: "string"}
              - {label: "Titel (EN)", name: "title_en", widget: "string"}
              - {label: "Text 1 (DE)", name: "p1_de", widget: "text"}
              - {label: "Text 1 (EN)", name: "p1_en", widget: "text"}
              - {label: "Text 2 (DE)", name: "p2_de", widget: "text"}
              - {label: "Text 2 (EN)", name: "p2_en", widget: "text"}
